### ISSUE TITLE
导出图注格式问题

### ISSUE THREAD

**Issue by Corgile** [Keldos-Li/typora-latex-theme#101]
## 需求描述

 导出后图注不显示的原因是什么呢，这个能解决吗？

## 需求原因

觉得有图注的话这个主题就更完整了

## 附加内容

试过将`:after`属性加在与图片相关的其他标签/`class` 上，但不起作用

**Comment by Keldos-Li** [comment]
能问下您具体是怎么做的吗？我之前图注都是手动在图片下面加`<span>`或者`<div>`的诶_(:з」∠)_

**Comment by Corgile** [comment]
> 能问下您具体是怎么做的吗？我之前图注都是手动在图片下面加`<span>`或者`<div>`的诶_(:з」∠)_

你好 就是取消注释了图注和表注相关的css，不是手动加的，估计是typoa的一个bug

**Comment by Keldos-Li** [comment]
被注释掉的的代码基本是有问题的、需要进一步调整的。css添加伪元素和class类在typora编辑界面不显示这个确实主要是typora的问题，要后面再看。
