### ISSUE TITLE
黑暗模式下导出的问题

### ISSUE THREAD

**Issue by zhuozhiyongde** [Keldos-Li/typora-latex-theme#104]
### 操作系统

macOS Ventura
Typora 1.4.8 (6558)

### 问题描述

使用 latex-dark 样式时
导出背景颜色不一致

### 复现方法

直接导出

### 预期行为

颜色一致

### 屏幕截图

![Cleanshot-2023-02-08-at-06 38 09](https://user-images.githubusercontent.com/36695271/217382789-05d89279-82be-42f0-9f9e-f9214b651f0a.png)

**Comment by Keldos-Li** [comment]
明白……这个因为一开始写的时候就没想着会有人用暗黑模式导出，所以没设相关的代码。我这几天看看。

**Comment by zhuozhiyongde** [comment]
笑死，我也一直没注意，都是用白色模式导出的
直到昨天晚上用黑色模式写完然后想着上床睡前看一看，为了眼睛导出个黑暗模式吧，这才发现问题
