### ISSUE TITLE
导出pdf格式会乱，该怎么解决呢

### ISSUE THREAD

**Issue by maihm6** [Keldos-Li/typora-latex-theme#112]
在typora里格式和字体是正确的，如下图
<img width="825" alt="image" src="https://user-images.githubusercontent.com/101976825/221790033-d3de67d0-b3f1-4ab8-93a7-31b6e87d6c1e.png">

但是da导出PDF后格式和字体就变了，如图
<img width="448" alt="image" src="https://user-images.githubusercontent.com/101976825/221789687-05582fdc-d4c6-48de-8af2-776fe10b91f3.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/101976825/221789835-d8d8c811-73c6-47e2-8fe4-8dec5d8883d6.png">
这种情况该怎么解决呢

**Comment by Keldos-Li** [comment]
![image](https://user-images.githubusercontent.com/23137268/221792124-34fe64d2-ce02-4d84-890c-3f275e9ddeed.png)

请在设置里确认一下这个有没选对。

**Comment by maihm6** [comment]
麦先生已收到您的来信，祝您生活愉快！

**Comment by maihm6** [comment]
> ![image](https://user-images.githubusercontent.com/23137268/221792124-34fe64d2-ce02-4d84-890c-3f275e9ddeed.png)
> 
> 请在设置里确认一下这个有没选对。

没有选自动选择，已经解决了，感谢
