### ISSUE TITLE
已安装家族宋，常规体却为楷体（斜体映成楷体、粗体为粗宋体等正常）

### ISSUE THREAD

**Issue by SSSayon** [Keldos-Li/typora-latex-theme#115]
### 操作系统

Windows 11 22H2 22621.1413

### 问题描述

安装了家族宋系列字体，常规体误映射为楷体。斜体映成楷体、粗体为粗宋体、粗斜体为粗楷体均正常。

### 复现方法

例如，以下是此 repo 的 readme 文件，容易发现常规体的字体出了异常。
<img width="506" alt="image" src="https://user-images.githubusercontent.com/47166440/227911738-3c79ad82-83d5-465b-81e7-7522c4c5dc0e.png">

**Comment by Keldos-Li** [comment]
印象里以前也有人和我反馈过这个问题，我后来更新过一版家族宋，要么就是蓝奏云忘了更新要么就是gitee没同步啥的……在github重新下载一下家族宋，重装字体试试。

**Comment by Jasonwi** [comment]
> 

在Windows11上我也遇到了这个问题，然后发现`base font` 要配置字体名，可以到word或者直接双击打开字体文件就可以看到，比如说`宋体-简` 的字体名是`Songti SC`
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/59698185/d27fbedd-9b95-424a-9a1e-7aef2dfa91ad)
那么，在`latex.css`文件中就可以配置为
```
--base-Chinese-font: "Family Song 常规体","Songti SC",
```
@Keldos-Li @SSSayon

**Comment by Keldos-Li** [comment]
不应该是这样的，我做字体的时候设置的字体名不是Songti SC……，而是Family Song或者FamilySong，Family-Song什么的（具体哪个记不清了）。我记得以前有一版有点问题，新的版本应该没这个问题……？

**Comment by liyangzbx** [comment]
> @Jasonwi 不应该是这样的，我做字体的时候设置的字体名不是Songti SC……，而是Family Song或者FamilySong，Family-Song什么的（具体哪个记不清了）。我记得以前有一版有点问题，新的版本应该没这个问题……？

为什么感觉家族宋字体有点模糊？

**Comment by Keldos-Li** [comment]
> 为什么感觉家族宋字体有点模糊？
> 
> 

矢量字体怎么会模糊呢，如果模糊那可能是Windows渲染显示的问题～
