### ISSUE TITLE
引用（单层&双层）中列表元素的间隙过大

### ISSUE THREAD

**Issue by LeoNicatot** [Keldos-Li/typora-latex-theme#121]
如图，引用中会出现列表项目之间存在很大的间隙，不知道是为什么，这个能和普通情况下的间隙统一起来吗？

<img width="772" alt="截屏2023-10-05 09 22 06" src="https://github.com/Keldos-Li/typora-latex-theme/assets/42774174/0c467130-7530-42d0-bc6b-adc81779f4e2">

**Comment by Keldos-Li** [comment]
马上就看（
