### ISSUE TITLE
多级列表显示效果错乱

### ISSUE THREAD

**Issue by Corona09** [Keldos-Li/typora-latex-theme#123]
### 操作系统
windows 11

### 问题描述
多层有序列表与无序列表嵌套时格式显示错乱

### 复现方法
如下图：
![image-20231108151713428](http://corona-oss.oss-cn-qingdao.aliyuncs.com/img/image-20231108151713428.png)

![image-20231108151729859](http://corona-oss.oss-cn-qingdao.aliyuncs.com/img/image-20231108151729859.png)

**Comment by Keldos-Li** [comment]
确实有这个问题。我研究一下。
