### ISSUE TITLE
压缩包里面没有target文件夹？

### ISSUE THREAD

**Issue by JohnChan1017** [Keldos-Li/typora-latex-theme#128]
这个压缩包里面的target文件夹是编译里面的scss生成的吗？

**Comment by Keldos-Li** [comment]
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/23137268/d135f6ab-7e1d-45f7-975b-0054e9a41821)
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/23137268/965edf97-c24e-4779-a0d8-48e62ce4b3ec)
应该从release中下载：https://github.com/Keldos-Li/typora-latex-theme/releases/tag/v0.3.0


或者，如果你想下载最新的主线编译，可以下载[这个包](https://github.com/Keldos-Li/typora-latex-theme/suites/18007279412/artifacts/1036109467)：
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/23137268/4e62d8bf-32a0-43ec-bef2-700e69b24207)
