### ISSUE TITLE
侧边栏滚动进度条能加入吗？

### ISSUE THREAD

**Issue by liyangzbx** [Keldos-Li/typora-latex-theme#133]
看不到进度条。

**Comment by Keldos-Li** [comment]
什么意思？

**Comment by liyangzbx** [comment]
> 什么意思？

就是像这种滚动条。Latex主题下看得到，Latex Dark主题下看不到，估计是黑色背景给覆盖到了？能否调整一下？
![Dingtalk_20240315104139](https://github.com/Keldos-Li/typora-latex-theme/assets/22143121/778c13d5-a462-4447-8780-5ca83500593e)

**Comment by Keldos-Li** [comment]
可以再对比一下Typora下的其他基本主题吗？如果其他主题也有这样的问题，那应该提给Typora。
