### ISSUE TITLE
这个主题的块引用方法与别的主题和编辑器不同，不兼容。

### ISSUE THREAD

**Issue by liyangzbx** [Keldos-Li/typora-latex-theme#134]
如题，一段文字，我要引用时，理论上只需要在段落前面加上>即可，现在我有一段文字，在前面加上>后，分别的vscode，notapad++以及typora其它主题测试，显示效果如下：
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/22143121/ca6eab9d-bca3-4e27-a6b5-f4e9d9f2ad9a)
但是在typora的latex这个主题下显示的效果是：
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/22143121/923fe59b-74d2-4e4d-b51d-912dc701a33a)
可以看到没有引用成功。发现，在latex这个主题下，块引用需要两个>>。
当我把这段文字前面加上两个>>时，latex显示如下：
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/22143121/dee744f7-2767-485b-bcb4-212b100f66ce)
但是，此时vscode,notepad++这些编辑器的显示就变成了这样块中嵌套一个块。
![image](https://github.com/Keldos-Li/typora-latex-theme/assets/22143121/6f5d4797-7028-4629-bef0-c05498fa0631)

别的编辑器和主题目前还没发现这个问题，就latex主题显得有点不兼容。能否修改下？

**Comment by Keldos-Li** [comment]
因为 LaTeX 自己本没有“引用”一说，也就没有这种前面加横条的quoteblock块的；而传统出版风格的引用一般是只有缩进并调整字体样式，所以 **默认只做了缩进的quoteblock样式** 。你在issue中说“ _可以看到没有引用成功_ ” 并不是这样的，你会发现这段文字的样式和正文并不一样。这其实是引用样式的一种体现。

但有些人又想要实现有明显块的quoteblock，所以又加上了这样传统样式的支持，用>>控制。

在源文件中可以看到注释：
https://github.com/Keldos-Li/typora-latex-theme/blob/2990266b4f3d92ac89d28dda78fe101e314aec8c/src/scss/blockquote.scss#L1-L28
这实际上是我提供的feature，不是bug。

但是“不兼容”确实是“不兼容”……如果你需要频繁在多种主题之间切换，还请选择你自己更常用的主题来撰写。

抱歉让你产生这样的疑问。
