### ISSUE TITLE
“文件-大纲”的字体、字号与编号问题

### ISSUE THREAD

**Issue by ywb1992** [Keldos-Li/typora-latex-theme#141]
首先非常感谢作者的项目！真的是相见恨晚😘😊，有了这个风格修饰，我再也回不到过去默认的 typora 样式了......真的是...太好看了😭！
但是，我在试图调整 css 设置以匹配我的风格时，发现：
（1）调整侧边栏的“文件、大纲”的**字体、字号**时无法通过修改以下代码段更改：
```
  /* 目录字体 */
  /* 默认调用 base-font */
  --toc-font: "";
  /* 默认调用 base-font-size */
  --toc-font-size: "";
```
我可能没有找到正确的代码段，并希望得到作者的帮助。
同时（2）在显示**大纲**时，似乎会从 0 开始编号，与正文不相匹配；（3）正文也偶尔会出现从 0 开始编号的情况（这在跨越层级生成标题时会出现，比如提供了“#”、“##" 和 "###"时，"###" 编号正常；但是如果仅提供 "#" 和 "###"，那么 "###" 就会编号异常）不知道这一问题是可解决的么？或者可否告知对应的代码段？
![image](https://github.com/user-attachments/assets/f2268d97-0024-465b-a60e-7fcc98229f09)
![image](https://github.com/user-attachments/assets/f7bdb6c1-9db2-4cbf-b194-f010067337db)

**Comment by Keldos-Li** [comment]
感谢厚爱！是这样的：

1. 目录指的是如果打 `[toc]`，typora出现的目录：
![image](https://github.com/user-attachments/assets/a748c3b2-943b-42b3-b611-8516f2af761f)

调整侧边栏请更改第22行的`--ui-font`：
<img width="553" alt="image" src="https://github.com/user-attachments/assets/1e506740-ff8b-4585-b035-36176de8fac8">

2. 大纲不应该出现和预览页面中不一致的编号……唔，这是因为你没有提供一级标题（单个#的，会居中的那种），所以出错了，我这两天去修正一下。

   跨越层级编号时出现的0吗……确实会如此，因为代码是有一个几级标题加一个几级标题的，故每级都是从0开始，我们认为这不算问题，因为本不应该跨越层级编号……其中省略的难道不应该就是0吗 QAQ 我想也许应该自动编成1……？我研究研究这代码好不好写，因为CSS没有那么智能哈。

**Comment by Keldos-Li** [comment]
我研究了一下，如果从默认编号是1，由于编号增加和展示是同时的，实际会变成从2开始编号，因此无法做到缺省某一级别标题默认为x.1.x。因此还是老老实实不要跨越层级吧。

**Comment by ywb1992** [comment]
非常感谢！问题都解决啦，再次感谢作者大大！（你的语气很萌，咳咳咳）
然后想再问问，如果希望更改公式的字体该怎么办呢？主要矛盾是，我感觉行内公式的字体太小，而行间公式的字体太大，但是似乎只能调整：
```
--math-font-size
```
进行全局修正，而不能在更细的粒度上面操作。想知道作者大大有办法么？

（然后其实我不知道应该直接在这里问还是应该新开一个issue？）

**Comment by Keldos-Li** [comment]
可以改，我没提供这样的设置，但确实可以强制改掉。

找到CSS里原本写着：
```CSS
.MathJax {
  font-size: var(--math-font-size);
}
```
的地方（大概在144行），改成例如：
```CSS
.md-inline-math .MathJax {
  font-size: 0.5em;
}
.mathjax-block .MathJax {
  font-size: 2em;
}
```
（这是一个夸张的字号倍数，行内公式为0.5倍正文字号，行间公式为2倍正文字号，你可以看着调整）

**Comment by ywb1992** [comment]
解决了！非常感谢！！！！☺️
