### ISSUE TITLE
调整全局字号大小后没有变化以及能不能在css里改变页面大小（默认的太小了）

### ISSUE THREAD

**Issue by wangguijiepedeval** [Keldos-Li/typora-latex-theme#143]
首先，感谢作者提供了如此精美的theme，
其次，在调整`--base-font-size: 9.5pt;`的时候，重启typora后无法生效，难道要重启电脑？；
最后，默认的页面大小在编辑模式的时候太小了，使用快捷键放大的方式个人觉得很奇怪，我曾尝试在css文件中改变`max-width: 21cm;`但同样无法生效。

**Comment by Keldos-Li** [comment]
你改动的地方都是正确的（字号和页面宽度），重启 Typora 即可，不应该不生效哇。你可以检查一下：
 - 是不是选择的正确的css文件，不要改了一个用的是另一个；
 - 确认编辑完保存了；

**Comment by wangguijiepedeval** [comment]
> 你改动的地方都是正确的（字号和页面宽度），重启 Typora 即可，不应该不生效哇。你可以检查一下：
> 
> * 是不是选择的正确的css文件，不要改了一个用的是另一个；
> * 确认编辑完保存了；

我在latex.css以及latexdark.css中都做了如下修改：
`--base-font-size: 16pt;`以及`max-width: 32cm;`
并且确认更改后保存以及重启了Typora，然而仍然没有一点改变……

**Comment by Keldos-Li** [comment]
不应该啊，或者是不是没有在typora的配置css文件夹里改而只是改了下载文件夹里的？太奇怪了，你可以改改其他内置主题的css看看能不能改😵‍💫
