### ISSUE TITLE
我想要把二级标题变成第x章这样的格式

### ISSUE THREAD

**Issue by DreamSpoonBird** [Keldos-Li/typora-latex-theme#145]
### 需求描述
我想要把二级标题变成第x章这样的格式，我该怎么做？

### 需求原因
学校要求是这个格式

**Comment by DreamSpoonBird** [comment]
我使用"第" counter(h2) "章";解决了

**Comment by Cooper1023** [comment]
#write h2:before {
  counter-increment: h2;
  content: "第" counter(h2) "章" "  ";
}

对应的地方修改为这段代码就可以了，最后那两个空格，代表在“第1章”与标题名称中间加两个空格，这个可以自己调整
