### ISSUE TITLE
关于macOS下英文正文字体和部分中文标题不正常显示的问题

### ISSUE THREAD

**Issue by Lzy-x-x** [Keldos-Li/typora-latex-theme#146]
系统是macOS 14.2.1。

问题：
1. 所有的英文正文都无法正常显示（一级标题居然显示正常）。在题目与摘要部分，只有标记了&lt;s&gt;的斜体Zhejiang University是正常显示的，其他部分全部变成了很宽的英文字体（包括标记了&lt;b&gt;的加粗文字）。这个问题在重装Latin Modern字体，然后重启typora后会消失，但是再重启一遍typora就又出现了。
2. 四级标题（即2.1.1这种）中文字体和模板不符（这个倒不怎么影响观感）

<img width="669" alt="截圖 2024-08-11 22 41 01" src="https://github.com/user-attachments/assets/39a5d2b9-6dde-41dd-bb0c-515e08fa9f67">
<img width="660" alt="截圖 2024-08-11 22 44 20" src="https://github.com/user-attachments/assets/1ef249e4-c8c8-469d-9928-5bd8b6319cab">

**Comment by Keldos-Li** [comment]
第一个问题的解决办法是在你的字体册中取消激活（或直接移除）Latin Modern Roman 字体的从 5 Regular 到 9 Regular 的所有样式，本来默认样式应该是 10 Regular。
<img width="1811" alt="image" src="https://github.com/user-attachments/assets/7e06064b-9d99-435a-8daf-4a31b45aa29d">

第二个问题，我没出现这种情况，可以看一下是不是自定义设置的问题，或者电脑中字体缺失。

**Comment by Lzy-x-x** [comment]
好的，已经解决了，十分感谢

**Comment by lkyu-ly** [comment]
> 第二个问题，我没出现这种情况，可以看一下是不是自定义设置的问题，或者电脑中字体缺失。

今天把typora从1.7.5升级到1.9的时候遇到了这个问题

<img width="1238" height="242" alt="Image" src="https://github.com/user-attachments/assets/6bdf4a41-1289-4125-b8a3-97599c242a79" />_1.9版本的标题_

<img width="1530" height="292" alt="Image" src="https://github.com/user-attachments/assets/aad2c4d9-78d4-44a0-8962-26c77bde6b54" />_1.7.5版本中同样位置的截图_

因为是覆盖安装所以系统和字体都没发生变化，我也尝试重装最新的主题文件，没有解决。typora设置中目前没看到独立的字体选项。

希望能得知是什么原因导致的，谢谢
