### ISSUE TITLE
导出word格式后 格式会退化到markdown原生样式？

### ISSUE THREAD

**Issue by leepand** [Keldos-Li/typora-latex-theme#15]

**Comment by Keldos-Li** [comment]
额，用pandoc导出word没办法的，除非自己再设置word样式模板（word和markdown底层就完全不一样）参见https://support.typora.io/Export/#word-docx 。
这是typora或者说所有markdown编辑器的问题，不是一个样式主题就能解决的。

如果希望用Word写LaTeX风格的文档，可以使用[WordTeX](https://www.andrew.cmu.edu/user/twildenh/wordtex/)直接在Word中编写。这个挺好用的，但可能要稍微调整下中文样式。

未来也许可能改一下word导出样式也放进去吧……但是这个就没法自定义了。

这个issue先放段时间吧，我怀疑还会有其他人也这么问。。。

**Comment by Keldos-Li** [comment]
#16

**Comment by Keldos-Li** [comment]
可以看看 #16

**Comment by leepand** [comment]
谢谢
