### ISSUE TITLE
基础项目有些好功能能否加上

### ISSUE THREAD

**Issue by sf88ux** [Keldos-Li/typora-latex-theme#152]
鸣谢

本项目是在下面两个开源项目的基础上完成的：

[yfzhao20/Typora-markdown](https://github.com/yfzhao20/Typora-markdown)
[du33169/typora-theme-essay_cn](https://github.com/du33169/typora-theme-essay_cn)

比如：
1.typora-theme-essay_cn项目的自动的序号为一、（一）1.（1），适用社会科学类论文，楼主的是纯数字的序号。
2.typora-theme-essay_cn项目有表格自动编号 和图片自动编号，楼主的项目舍弃了这个功能。
3.楼主的项目能否实现图片和表格自动编号 ，但编号后还能自己加名称，比如"图3 2023年北京市气候变化图"，其中"图3"是自动生成的，"2023年北京市气候变化图"由用户自己添加,并且支持pdf导出。

**Comment by Keldos-Li** [comment]
图片表格自动编号在导出时会失效，所以去除了这个功能。

**Comment by sf88ux** [comment]
就算pdf导出要失效，图片表格自动编号功能能否放着不要去掉。方便自己手工加的标题"图xx  XXX"和自动生成的图xx能够进行对比，方便核对图的顺序。

**Comment by sf88ux** [comment]
额，楼主，那序号的问题能否解决一下，这个比较刚需。纯数字序号没法用，我看essay的主题就是纯中文序号
