### ISSUE TITLE
适用于 APA 格式参考列表的 HTML 格式

### ISSUE THREAD

**Issue by QianFuv** [Keldos-Li/typora-latex-theme#157]
```
<p style="padding-left: 2em; text-indent: -2em;">
xxxxx
</p>
```

斜体使用`<i>xxxx<i/>`

**Comment by QianFuv** [comment]
建议在Wiki里提一下
毕竟有些论文参考文献要求是 APA 格式

**Comment by RalXYZ** [comment]
您的意思是否是：

有些课程要求，论文中的参考文献需要根据 APA 格式排版。由于课程没有对论文有非常严格的格式规范要求，因此可以用我们这个非专业主题写论文。但同时，APA 格式的排版有一个很明显的特点，即，从第二行起有“缩进”；然而，我们这个主题并没有对这样的情况给出解决方案。

您提出的解决方案是，可以在 markdown 文件中嵌入 HTML，从而近似地实现 APA 格式排版（至少大体上看起来没问题）。你给出了一个方法，解决了这个排版中的缩进和斜体的问题。如，对于引用：

> Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change. Psychological Review, 84(2), 191–215. https://doi.org/10.1037/0033-295X.84.2.191

可以在 markdown 文件中插入形如下面的 HTML 代码段：

```html
<p style="padding-left: 3em; text-indent: -3em;">
Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change. <i>Psychological Review</i>, 84(2), 191–215. https://doi.org/10.1037/0033-295X.84.2.191
</p>
```

从而近似实现 APA 格式的参考文献排版：
![APA format result screen-shot](https://github.com/user-attachments/assets/a63fc589-6084-4b44-a52f-fd490f79e72d)

您探索出了这一途径，现在将这一经验贡献给我们，希望我们能将这一经验添加到项目 Wiki 里。

您的意思是这样吗？

**Comment by QianFuv** [comment]
是的是的😊😊😊

**Comment by RalXYZ** [comment]
@QianFuv  已在[相关wiki文档](https://github.com/Keldos-Li/typora-latex-theme/wiki/%E4%B8%AA%E6%80%A7%E5%8C%96%E8%AE%BE%E7%BD%AE#apa)中提交了您的贡献，并在该提交中将您署名为 author，参见[提交记录](https://github.com/Keldos-Li/typora-latex-theme/wiki/%E4%B8%AA%E6%80%A7%E5%8C%96%E8%AE%BE%E7%BD%AE/_history)。
如果您对此结果满意，请您关闭此 issue。

**Comment by QianFuv** [comment]
建议改为`style="padding-left: 32pt; text-indent: -32pt;"`
![image](https://github.com/user-attachments/assets/aaa6cb4c-4350-4c8e-97f5-2b7a48682707)

**Comment by QianFuv** [comment]
`0.5in`也行
`0.5 in = 0.5 x 72 pt = 36 pt`

**Comment by RalXYZ** [comment]
> 建议改为`style="padding-left: 32pt; text-indent: -32pt;"` 

这个，我们在前期调研过了，参考过 APA 规范中要求的 0.5 英寸缩进。但我们选择不严格按照这一规范执行。这是因为：
- 一般地，APA 要求引用的字号为 12pt，但本主题的正文字号是 10pt。这会导致，如果在本主题里，APA 仍然按照 0.5 英寸缩进，那么缩进的长度就会**看起来**比 APA 标准要多。
- 因此，缩进的长度也应该对应地简短，来匹配我们更小的字号；这样，排版结果才能**看起来**和 APA 格式差不多。

这也是为什么我一直强调，本主题给出的 APA 格式解决方案只是一种**近似**。如果我们严格按照某一种特定格式做调整，导致的很可能是对整个排版的大改——我认为，这对于一个业余主题是没有必要的。

**Comment by QianFuv** [comment]
好的麻烦啦 那就按原来的样式就OK

也有一部分我的原因，因为我改成APA的字号后看不出区别😢
