### ISSUE TITLE
自定义模板的方法

### ISSUE THREAD

**Issue by sky5454** [Keldos-Li/typora-latex-theme#16]
https://chuhong.life/007-markdown-to-docx-pdf/#%E4%B8%80%E8%88%AC%E6%A0%B7%E5%BC%8F%E7%9A%84%E8%BD%AC%E6%8D%A2

可以修改模板为你需要的样式，包括但不限于加页眉等

然后在 `Typora` 里设置pandoc的额外参数为` --reference-doc=模板路径.docx`即可。
路径支持相对路径（相对于当前要导出的md文件）

我现在用它来交作业，非常fine，真的fine

**Comment by Keldos-Li** [comment]
是的我知道这个方法。但我觉得Word里面调整样式麻烦就没做过——既然最终成品要word（latex）那为什么不直接用Word（latex）上手呢🥲🥲，所以要求word的作业我就直接用wordtex。。。

不过看需求之后再看看要不要做一下word模板吧……你有好用的模板也可以挂到自己的github上或者推到这个仓库都可以。
