### ISSUE TITLE
和公式相邻的文字会被莫名拉伸

### ISSUE THREAD

**Issue by 2018liuzhiyuan** [Keldos-Li/typora-latex-theme#165]
### 操作系统
windows11. typora 1.9.5

### 问题描述
和公式相邻的文字会被莫名拉伸

### 屏幕截图
![image](https://github.com/user-attachments/assets/bf15d473-808a-4938-bcf1-debb4a6d9c3d)
源代码:
![image](https://github.com/user-attachments/assets/74ca43b9-cb35-49a1-a43a-4f3cdb4a902d)

**Comment by RalXYZ** [comment]
@2018liuzhiyuan hi，邮件已经回复你了，请问还有什么进一步的问题吗？
如果没有进一步的问题，三天后我就把这个 issue 关掉了

**Comment by 2018liuzhiyuan** [comment]
没有问题了，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月25日(周一) 晚上11:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Keldos-Li/typora-latex-theme] 和公式相邻的文字会被莫名拉伸 (Issue #165)




 
@2018liuzhiyuan hi，邮件已经回复你了，请问还有什么进一步的问题吗？
 如果没有进一步的问题，三天后我就把这个 issue 关掉了
