### ISSUE TITLE
代码块没有行号？

### ISSUE THREAD

**Issue by Robotxm** [Keldos-Li/typora-latex-theme#17]
![image](https://user-images.githubusercontent.com/5405331/124151194-df50ed00-dac4-11eb-8f52-180da7473b5d.png)

不知道是不是我打开方式不对，编辑和导出的 PDF 都没有行号

**Comment by Keldos-Li** [comment]
哦哦，我发现了，在macOS和一些Unix的系统里是有行号的，在Windows上似乎没有……
因为现在没有写代码块中和行号相关的代码，是调用markdown基本渲染方式，sorry。

**Comment by Keldos-Li** [comment]
emm，这么多天竟然没人回答你，太惨了。。
你要在偏好设置里面打开行号，像这样：
<img width="927" alt="iShot2021-07-05 23 47 30" src="https://user-images.githubusercontent.com/23137268/124497049-df1a5f80-ddec-11eb-8c7b-3077dcbb087e.png">
