### ISSUE TITLE
多行公式的公式块无法自动编号

### ISSUE THREAD

**Issue by gengdd** [Keldos-Li/typora-latex-theme#19]
如题，不知道是否可以解决，不行的话就每一个写一个公式块。

![image](https://user-images.githubusercontent.com/18337863/129438607-89f3ee44-e902-4f3a-a08a-8fa4ee7bdc07.png)

**Comment by Keldos-Li** [comment]
首先，这个问题和本项目无关，如果有问题最好可以查看typora的mathjax公式支持相关文档。看看这个：https://support.typora.io/Math/#auto-numbering

然后多行公式是可以自动编号的，不知道你哪里写的不对。您的issue太简洁了。这里提供我的样例以供参考：
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/23137268/129440592-d9ff28e0-d91a-4bf1-9e34-f15e43029360.png">

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/23137268/129440645-da046da2-67f4-4ead-880e-5282b7f3246c.png">

<img width="979" alt="image" src="https://user-images.githubusercontent.com/23137268/129440765-15fd262f-a1a8-4e01-8b23-a475ad855c5c.png">

当然，其他LaTeX的环境同理，比如`case`和`together`。

最重要的是，您要是希望自动编号，您应该在偏好设置中勾选了“自动添加序号”选项。否则您应该手动在某行公式中添加`\tag{1}`之类的标签。

sample放在下面👇🏻：
[sample.md](https://github.com/Keldos-Li/typora-latex-theme/files/6986203/sample.md)

**Comment by gengdd** [comment]
@Keldos-Li 收到！！谢谢您的耐心回复！！！
