### ISSUE TITLE
显示安装成功后，typora主题文件夹仍找不到该主题

### ISSUE THREAD

**Issue by mancuoj** [Keldos-Li/typora-latex-theme#24]
![image](https://user-images.githubusercontent.com/45707684/131337650-466a4148-a391-4392-b0e9-99ff1865f1db.png)
![image](https://user-images.githubusercontent.com/45707684/131337766-48cad3ba-0ef9-4c25-89e7-4c296b393999.png)

**Comment by mancuoj** [comment]
找到了非scss的发布地址，已解决

**Comment by RalXYZ** [comment]
感谢反馈。  
未来会在 README 中写清楚手动安装方案。

**Comment by RalXYZ** [comment]
尽管没有定位到脚本里的问题，但我在文档里添加了**手动安装**的方案：   
- 如果自动安装出现问题，您也可以选择进行**手动安装**。请您打开安装包的 `target` 文件夹，按照[官方教程（英文）](https://theme.typora.io/doc/Install-Theme/)，将这个文件夹里的所有 CSS 文件复制到指定的 Typora 主题文件夹中。  

> 找到了非scss的发布地址，已解决  

Release 里的压缩包中的内容本身就已经是构建结果了（构建结果 指 从 SCSS 转译出来的 CSS），您直接下载 Release 里的最新安装包，复制里面的 CSS 文件即可。
