### ISSUE TITLE
主题使用GPL协议是否意味着使用这份主题的文档必须以GPL协议开源？

### ISSUE THREAD

**Issue by leoleoasd** [Keldos-Li/typora-latex-theme#27]
如题，觉得有必要探讨一下。

当然，如果单纯markdown文件，显然不收到gpl传染性的限制。但是，如果是用这份主题导出的html or pdf文件呢？

导出的html显然带有这份主题的代码，按照我的理解需要以gpl协议开源（~~虽然讨论html是否需要开源没有意义~~）。打印的pdf应该也是用导出的html渲染出来的，不确定是否需要一起开源。

**Comment by RalXYZ** [comment]
这是一个值得思考的问题。  

事实上，在自由软件与 GPL 协议的历史上，就有不少人提出过类似的争议。比如，GNU Bison 以 GPLv2 许可证开源，但是由 Bison 生成的代码往往被我们的项目直接使用，这使得不少人质疑使用 Bison 中间代码的项目是否也应以 GPLv2 开源。再比如，一些 C 的宏定义或 C++ 的模板，在编译期会发生展开（即发生了事实上的**内嵌**，而不是一个**引用**）；这使得，即使被使用的宏定义或模板来自一个 LGPL 库，它也可能必须以 GPL 开源。 
针对上述争议，一个统一的解决方案是“GPL+附加条款”。以 GPLv3 为例，其原文如下：  

> 7. Additional Terms.
> “Additional permissions” are terms that supplement the terms of this License by making exceptions from one or more of its conditions. 

在刚刚举出的不少案例中，仓库的维护者依照 GPL 协议，在每一个源文件的起始部分都注明了附加条款。以 Bison 为例，它的附加条款的大意是：只要不修改 Bison 输出的结果，那么你就可以把 Bison 生成的中间码当做你的项目的一部分，且你有权自由选择这个项目的许可协议。  

根据以上前人的经验，我做出以下判断：  
由我们的主题生成的 HTML 与 PDF 是否应该以 GPLv3 开源存在争议；为了消靡这类争议，我们可以考虑为我们的源文件加上附加条款。

**Comment by Keldos-Li** [comment]
😢这个思考太深刻了……可以以后讨论……虽然实际讨论用它做的文档是否开源意义确实不大……

不过导出的PDF应该不带源码了，typora是用了pandoc或者Chromiun或者WebKit把HTML的页面信息再编码成postscript控制的（应该），应该只带有绝对信息，不再包含CSS代码了。（如果不对欢迎指正）

所以PDF应该也是不用管开源的问题的吧_(:з」∠)_

**Comment by RalXYZ** [comment]
下一步会统一解决一下与协议相关的问题，包括目前仓库里 其他仓库的 MIT 协议的问题也要解决。

**Comment by RalXYZ** [comment]
我拟了一份：  
As a special exception, you may create a larger work that contains part or all of the Typora Latex Theme and distribute that work under terms of your choice, so long as that work isn't itself a CSS theme or a generator of CSS theme. Alternatively, if you modify or redistribute this CSS theme itself, you may (at your option) remove this special exception, which will cause the CSS theme and the resulting output files to be licensed under the GNU General Public License without this special exception.
