### ISSUE TITLE
Format bug for nested and numbered lists

### ISSUE THREAD

**Issue by Co1lin** [Keldos-Li/typora-latex-theme#42]
A weird indent appears for nested and numbered lists as below.

Markdown code:

```markdown
Key points:

1. Market Value:
    1. GDP
    2. Housing
        1. rental housing
        2. owner-occupied housing
    3. Public services are included
    4. Excludes products that don't enter a (legal) market
        1. illegal drugs
        2. products produced and consumed at home
        3. ???
        4. ???
        5. ...
2. Final goods
```

Screenshot:

<img width="248" alt="Screen Shot 2021-11-15 at 7 54 59 PM" src="https://user-images.githubusercontent.com/17642707/141777972-7c7d3767-61c7-46f9-a8f4-2fffae0b442e.png">

Other markdown themes like "Newsprint" do not have this issue.

**Comment by Keldos-Li** [comment]
是我的问题。因为模仿了LaTeX的编号，所以全部样式是自定义的。最麻烦的是LaTeX的编号是右对齐的，为了实现这点，我把项目符号放在了一个固定宽度的“盒子”里来右对齐，这个合适的宽度在最初的版本里是由我反复试出来的，一开始没有太多问题。

现在这个情况应该是在某一次我调大了默认正文字体和行距，导致“盒子”宽度与行距不匹配引起了错行对齐。如果你缩放Typora到一个小比例，就会发现它又正常了：
<img width="924" alt="image" src="https://user-images.githubusercontent.com/23137268/141781144-ed21987e-b4fd-40a4-a8c2-aa6fe6ffb61d.png">
现在默认缩放时确实有问题。希望我能有空及时修一修。应该可以改成和行距变量相关的函数。

其实整个项目列表的CSS写的就不是很好，我之前也没找到太合适的方法，这个坑得慢慢填了，我对不起大家呜呜呜。

------

临时的解决办法应该是缩小或增大行距（以0.5的模数来增减吧）_(:з」∠)_等我做完这个小组展示的内容先啊啊啊您或许可以先自己试一试对不起我好多事情啊啊救命

**Comment by Co1lin** [comment]
感谢回复！项目已经很不错了，祝您早日赶完 DDL ！

**Comment by RalXYZ** [comment]
尚未检查出原因，重新打开
