### ISSUE TITLE
PDF output bug for multiline links

### ISSUE THREAD

**Issue by zhzh2001** [Keldos-Li/typora-latex-theme#50]
### 操作系统
Windows 10 Home China 21H1
Typora v0.11.18

### 问题描述
如果一个链接跨行，整个段落都会成为超链接，显示点击的鼠标图标，而且无法选中文字。

与 PDF 阅读器无关，Typora 导出 HTML 也不受影响。

![image](https://user-images.githubusercontent.com/24852958/143669053-a4715b7a-37d4-44a9-9b29-c16da8081ba5.png)

### 复现方法

输入类似内容并导出为 PDF。

![image](https://user-images.githubusercontent.com/24852958/143669076-ce8918b5-dc7f-4a2b-89a6-32d2d9fb05ce.png)
![image](https://user-images.githubusercontent.com/24852958/143669079-89751d3c-8970-427b-8383-33fd86b5ee09.png)

### 预期行为
仅在超链接区域内可以点击，并可以选中超链接文本和段落其他文本。

**Comment by Keldos-Li** [comment]
经测试，该版本 Typora 使用其他主题导出 PDF 也会出现此情况，故这个 bug 是 Typora 的问题，不是我们这个主题能够解决的。您可以去 https://github.com/typora/typora-issues 报告该问题。

**Comment by zhzh2001** [comment]
哦，确实，我之前测试其他主题的方法有误，打扰了。

但现在 Typora 的情况，就不管它了，谁让它要收费呢（
