### ISSUE TITLE
Better math equation support

### ISSUE THREAD

**Issue by zhzh2001** [Keldos-Li/typora-latex-theme#54]
### 需求描述
现在用 Typora 生成的数学公式无法选择文字，基本就是图片，比较难受。不确定是否可以采用 Mathjax 或 KaTeX 等，使公式中的字符可以被选中。

当然这个需求恐怕有点困难，毕竟 Typora 都没实现。

### 需求原因
美观考虑，同时更加接近 LaTeX 排版的效果。我认为现在公式是本主题与真正的 LaTeX 排版间最大的差距了。

### 附加内容
现有：
![image](https://user-images.githubusercontent.com/24852958/143686288-44314971-565b-40c3-bdac-c3260a959e78.png)

预期效果：
![image](https://user-images.githubusercontent.com/24852958/143686318-79e1019c-45f8-4c8c-81b2-ff8d396ff1f2.png)

或者 Hexo 的效果：
![image](https://user-images.githubusercontent.com/24852958/143686348-03572d9e-10e4-4849-a430-8109805eeaec.png)

**Comment by Keldos-Li** [comment]
参看https://support.typora.io/Math/

**Comment by Keldos-Li** [comment]
就是说，typora是用的mathjax……但导出时是会变成svg图像……

真的这种东西还是比较底层的，我们大概率是实现不了的_(:з」∠)_……所以请给typora提issue……至于付费了么…

**Comment by Keldos-Li** [comment]
![image](https://user-images.githubusercontent.com/23137268/143690497-c23e8e77-7bab-4553-b705-ed1cd049e5d3.png)
Typora 把mathjax的渲染模式定死了，应该是他们的考虑……
