### ISSUE TITLE
导出 PDF 时，换页处会出现文本被切断的情况

### ISSUE THREAD

**Issue by hotarugali** [Keldos-Li/typora-latex-theme#57]
### 操作系统
![image](https://user-images.githubusercontent.com/32862896/143976520-dcc84262-cf36-4fa4-8bc3-beb8a9b76667.png)

### 问题描述
在这个主题下，用 typora 自带的 PDF 导出功能时，换页会出现文本被切断的情况。
![image](https://user-images.githubusercontent.com/32862896/143976917-1884b317-335f-4a31-8ed9-ee1bf435301c.png)

**Comment by RalXYZ** [comment]
请问您方便将造成这个 bug 的 markdown 文件发给我们吗？  
如果您方便的话，直接发到 @Keldos-Li 和 @RalXYZ GitHub 主页中的邮箱就行。

**Comment by RalXYZ** [comment]
hotarugali 你好！  
我刚刚尝试复现你描述的问题。我尝试的方法是在引用块里增加一段 LaTeX 公式，但并没有复现你出现的问题。我的复现结果已经被放在附件中了。我在使用 Linux 版本的 Typora ，主题的版本号是 `v0.2.6`。

如果你愿意，可以把你遇到问题的文档分享给我们。如果你使用了合适的浏览器，你可以直接把文档拖动到 issue 的评论框中，这样就可以将文件上传到这条 issue 的上下文中。如果有隐私相关考虑，你也可以将文档私发给 @Keldos-Li 或 @RalXYZ  的邮箱，我们会保护你的隐私信息。  

如果这个 issue 在未来一周内没有进展，那么我很有可能会关闭它。  

### 附件

![image](https://user-images.githubusercontent.com/19510622/145680135-3c9fcd52-ba45-40cd-8f5f-516138214b51.png)
![image](https://user-images.githubusercontent.com/19510622/145680172-81837564-fef4-41a2-b907-a48534408e1f.png)

**Comment by hotarugali** [comment]
作者你好，我的 markdown 文档已经发到 @Keldos-Li 邮箱了。报歉，最近事情比较多没有及时回复。

**Comment by beetcb** [comment]
![image](https://user-images.githubusercontent.com/63141491/145792150-d438f9f8-15d1-4162-ab50-e24894a6be35.png)

我遇到过几次阶段问题，这个切断一般都是在换页才能复现

我目前发现可以通过强制换行临时解决，希望能有所帮助 @RalXYZ

**Comment by Keldos-Li** [comment]
> ![image](https://user-images.githubusercontent.com/63141491/145792150-d438f9f8-15d1-4162-ab50-e24894a6be35.png)
> 
> 我遇到过几次类似的截断问题，这个切断一般都是在换页上一行才能复现
> 
> 我目前发现可以通过强制换行（是 CSS 规则, 不是 CRLF / LF）临时解决，希望能有所帮助 @RalXYZ

是的，这种小标题的截断是可以被复现的。目前我初步认定这是行距、字体大小、页边距、Typora预设CSS和Typora转PDF引擎（WebKit与pandoc等）各方存在冲突的结果，而如果转成HTML在打印似乎就不会出现这种小的截断，具体啥冲突了有待进一步排查。

**Comment by Keldos-Li** [comment]
@hotarugali 公式的截断是目前我不能够在typora中复现的。我使用您的文件在我Mac本地环境下导出之后，并没有任何的公式（或其他区域元素）被截断。我不理解。。。

或许 @RalXYZ 可以用pandoc导出PDF试一试，（？）不是很清楚是否和操作系统有关。（？）🥵

**Comment by jamekuma** [comment]
![image](https://user-images.githubusercontent.com/42855938/146420924-44c1c0dd-cd75-4738-b375-332dd30b1c1d.png)
我的系统是windows 10，typora版本为0.9.96，增加公式块行数使其跨页后，复现出了以上的结果，字母"x"被两页截断。

与之对比的，使用typora自带的“github”主题，其虽然也存在矩阵被截断情况，但字母不会被两页截断：
![image](https://user-images.githubusercontent.com/42855938/146422061-5dbca134-d7eb-4014-9361-a0152b22f9b2.png)

**Comment by RalXYZ** [comment]
@hotarugali
非常非常感谢您的配合！根据您邮件中发来的文件，我终于发现了问题所在。以下，我会描述我分析这个 bug 的完整思维过程。

### 思考的开始

刚刚拿到您的文档时，我直接使用我的设备导出，然而并没有发现任何问题。公式块确实出现了跨页的案例，但是文本并没有被异常地切断。这时，我判断，这大概是由于一些巧合，导致问题并没有被显现出来。于是，我进行了一些额外操作，展开了对问题的定位。

### 问题的定位

我发现，您的文档中有引入若干图片，且是用 HTML 标签的方式引入的。比如下面这段 HTML 代码：

```html
<img src="./code/5.1-d-1.png" alt="5.1-d-1" style="zoom:10%;" /> 
```

于是我产生了怀疑。因为，我们可以用 HTML 自由调节图片的宽度和高度，而 HTML 又被嵌入到了 markdown 里，我怀疑这会导致 Typora markdown 到 HTML 转译器的一些混乱，从而有可能导致错误的文字切割。

为了验证我的这一猜想，我把上述 HTML img 进行了一连串的 `height` 微调：

```html
<img src="./code/5.1-d-1.png" alt="5.1-d-1" height="4500" width="5000" style="zoom:10%;" />
<img src="./code/5.1-d-1.png" alt="5.1-d-1" height="4600" width="5000" style="zoom:10%;" />
<img src="./code/5.1-d-1.png" alt="5.1-d-1" height="4850" width="5000" style="zoom:10%;" />
```

可以看出，我在反复修改 `height` 的值，并且查看分页处公式是否出现问题。果然，最终，在某个特定的 `height` 下，公式在分页处的文本被截断了：

![image](https://user-images.githubusercontent.com/19510622/146485090-bc7dae58-c8b4-44b2-b4d4-967f0aad6f70.png)

 
这样，我就成功地完成了对您提到的问题的定位。

### 这个问题应该由我们负责吗？

我切换到了 Typora 官方的 GitHub 主题。在我又进行了一番 `height` 的微调后，官方主题出现了一模一样的问题：

![image](https://user-images.githubusercontent.com/19510622/146484875-8f1e77c4-d3de-4ccf-aa91-11411d894f11.png)
 
 **因此，这个问题不该由我们负责。这是 Typora 的一个 bug。**
 
 ### 我们该如何做的更好？
 
 鉴于这个问题的原委终于水落石出，我们**一定**会将这一行为写在我们的帮助文档中，帮助所有后来者认知到这一问题。我们也会考虑向 Typora 官方提交 issue。
 
再次感谢您在百忙中为开源项目做出贡献！

**Comment by RalXYZ** [comment]
@jamekuma 
谢谢！请参考[上面的评论](https://github.com/Keldos-Li/typora-latex-theme/issues/57#issuecomment-996413400)，我认为我已经找到了问题所在。

**Comment by Keldos-Li** [comment]
太强了 @RalXYZ

**Comment by RalXYZ** [comment]
这一问题已被记录在 wiki 的 FAQ 中。
