### ISSUE TITLE
Enhance quote block style

### ISSUE THREAD

**Issue by RalXYZ** [Keldos-Li/typora-latex-theme#58]
### 需求描述
讨论是否有必要更改引用块的样式；若确有必要，则进一步确定该使用何种样式。

### 需求原因
目前，我们的引用块仍然保持着 GitHub markdown 的较为原始的样式。  
然而，我最近在阅读了一些文献后，发现了以下引用块的样式：  

![image](https://user-images.githubusercontent.com/19510622/144010060-708d99df-39de-40c7-bc67-9f29889049d8.png)

即，使用了横线与斜体。我认为这值得参考或采纳。   

### 附加内容
该文献中有很多引用块的用例，请参阅它的在线预览版本 [RISC-V Privileged Architecture](https://riscv.org/wp-content/uploads/2017/05/riscv-privileged-v1.10.pdf)。

**Comment by RalXYZ** [comment]
我们目前的引用块的颜色是灰色，然而我不认为较为正式的论文里会出现这种颜色。所以，我认为，无论如何，引用块的样式都需要进行修改，比如至少把它变为纯黑色。  

![image](https://user-images.githubusercontent.com/19510622/144011154-a47a65b1-7d1f-4e59-942e-983e3fb673ac.png)

**Comment by Keldos-Li** [comment]
不是很确定论文会怎么采用段落引文的格式……我研究下……

颜色确实应该是黑色
