### ISSUE TITLE
第三级的有序编号之间不对齐

### ISSUE THREAD

**Issue by jamekuma** [Keldos-Li/typora-latex-theme#63]
### 操作系统
Windows 10, 家庭中文版, 20H2

### 问题描述
第三级的有序编号(i, ii, iii, iv, ...)之间不对齐。

### 复现方法
1. 使用有序编号
2. 使用Tab键，得到多行 第三级编号(i, ii, iii, iv, ...)
3. 得到bug

### 预期行为
第三级的有序编号的右侧应该是对齐的。

### 屏幕截图
bug的截图如下：
![image](https://user-images.githubusercontent.com/42855938/146668581-41027543-25f2-46e2-ac34-55888505459d.png)

**Comment by RalXYZ** [comment]
Jianyu 你好！
#42 中的情况看起来与您描述的比较相似。
鉴于已经很多用户遇到了这个问题，我们会尝试排查并解决这个问题。

**Comment by RalXYZ** [comment]
此外，请问您是否方便把遇到问题的文档发给 @Keldos-Li  或 @RalXYZ 的邮箱中？这能帮助我们更快地定位到问题。
如果您对隐私相关问题有顾虑，您可以事先删除您文档里的所有身份信息。我们会尊重并保护您的隐私。

**Comment by jamekuma** [comment]
谢谢，我的文档内容和 #42 中的是一样的，确实是同样的问题
