### ISSUE TITLE
README的图出问题了！！！

### ISSUE THREAD

**Issue by Immortal-Sty** [Keldos-Li/typora-latex-theme#70]
Gitee 做了防盗链，所有在 Gitee 的图，在引用时都变成了 Gitee 的图标，大佬还是把图挪到 GitHub 吧。

**Comment by Keldos-Li** [comment]
知道了知道了，你看我昨天就修了一下发了pull request，不过Ralph提醒我仓库减少二进制文件，所以没merge。
今天忙着建模，等我清明节放假在GitHub开个仓库放图片哈~

**Comment by RalXYZ** [comment]
感谢感谢，我们正在处理

**Comment by RalXYZ** [comment]
https://github.com/Keldos-Li/typora-latex-theme/pull/71 已解决
