### ISSUE TITLE
导出PDF时无法呈现粗体和斜体

### ISSUE THREAD

**Issue by deepbluefantasy** [Keldos-Li/typora-latex-theme#74]
### 操作系统

Windows 10

### 问题描述

导出为PDF时无法显示粗体和斜体，设置为粗体和斜体的文字会在PDF中呈现为正常字体。

我尝试过先将Markdown文件导出为HTML，然后再生成PDF。这样导出的PDF仍然无法呈现粗体和斜体。

### 预期行为

正常呈现粗体和斜体。

**Comment by RalXYZ** [comment]
感谢你的反馈！♥  
我刚刚在我的 Windows 设备上测试了一下，发现斜体的导出结果确实是常规样式，而黑体的导出时符合预期的。我印象不是很清楚了，@Keldos-Li 我们以前有没有 对斜体的导出 进行过特殊处理？  
@deepbluefantasy 目前我能给出的建议是，先确认 Typora 和 主题 都升级到了最新的版本，并[安装我们推荐的字体](https://github.com/Keldos-Li/typora-latex-theme/wiki/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B#%E5%AE%89%E8%A3%85%E5%AD%97%E4%BD%93)。如果以上尝试都没有效果，我们再继续进行沟通。

**Comment by Keldos-Li** [comment]
可以看看typora页面和导出PDF的截图吗

**Comment by deepbluefantasy** [comment]
我的Typora是最近更新的1.2.5，而下载的主题是你们1月左右的发现版（应该就是最新的，我是上个星期才开始接触你们这个项目的）。

我已经按照您项目中的要求，下载了您蓝奏云中“家族宋”这个压缩包，并在解压后将字体文件放入了`C:\Windows\Fonts`这个文件夹。

但是bug仍然存在。我查看了附录中的`sample.md`和`sample-chinese.d`这两个样例，发现他们转换出的PDF中均存在此问题（即英文和中文的粗体和斜体都无法呈现）。因此推测不是字体造成的。

以下是`sample-chinese.md`与其PDF版本截图：

---

![image](https://user-images.githubusercontent.com/34130942/164592261-65a7e133-3f38-4ccf-b25e-5cc02fc65608.png)


---

![image](https://user-images.githubusercontent.com/34130942/164592174-501c66b8-eb94-4ce0-9a9b-e8161ec397d1.png)

---

我注意到引用语句中的斜体和粗体是正常的，这可能是问题的切入点。

**Comment by RalXYZ** [comment]
我进行了检测，在我的 Windows 设备上行为如下：
- Typora 编辑界面，可以正确显示斜体。
- Typora 直接导出的 PDF ，无法正确显示斜体。
- Typora 直接导出的 HTML，可以正确显示斜体。
- 将上述 HTML 使用 Chromium 内核浏览器导出到 PDF，可以正确显示斜体。
根据以上我能直接获取的信息，我倾向于认为这是 Typora 本身的问题。我会进一步展开调查。

你有提到：
> 我尝试过先将Markdown文件导出为HTML，然后再生成PDF。**这样导出的PDF仍然无法呈现粗体和斜体。**
我想知道，你是用什么工具把 HTML 转换成 PDF 的呢？

**Comment by Keldos-Li** [comment]
好怪，等我今天考试考完我就来好好看看。

您可以先卸载下家族宋看看，那个字体的实际应用我应该还没有写进发布版的css（虽然我自己已经用了三个月没有出问题），不排除可能会有bug，毕竟是自己打包的字体，可能有些  Windows 相关的 property 没写对。

**Comment by deepbluefantasy** [comment]
我的Windows设备行为如下：

- Typora 编辑界面，可以正确显示斜体和粗体。
- Typora 直接导出的 PDF ，无法正确显示斜体和粗体。
- Typora 直接导出的 HTML，可以正确显示斜体和粗体。
- 将上述 HTML 使用 Chromium 内核浏览器导出到 PDF，无法正确显示斜体和粗体。

---

辛苦！

**Comment by RalXYZ** [comment]
明白了，那么能不能把导出的这个 HTML 发送到我的邮箱中呢？  
我的邮箱在 github 主页里有写😉

**Comment by Keldos-Li** [comment]
[让幻想飞](https://github.com/yfzhao20/Typora-markdown/commits?author=yfzhao20)大佬说可以试一下重新安装文档用到的字体，或许可以浅试一下；emm也可以试试换github默认主题看看导出是不是有问题，如过还不行那应该就是Typora的问题了。不好意思最近没Windows环境。。。（同时没有新版本typora的win版本）

**Comment by deepbluefantasy** [comment]
>

> 明白了，那么能不能把导出的这个 HTML 发送到我的邮箱中呢？ 我的邮箱在 github 主页里有写😉

[啊不好意思，之前忙着写作业，忘了这回事儿了。已经通过邮箱把发送给您了，您也可以下载这个：[sample-chinese.zip](https://github.com/Keldos-Li/typora-latex-theme/files/8599073/sample-chinese.zip)

另外，我之前是打算用您的样式写一个课程作业。不过因为ddl到了，所以我用了另外一个样式。所以如果解决不了这个问题也没关系，谢谢啦~

**Comment by Keldos-Li** [comment]
太难过了😫，抱歉没能在您的ddl前解决这个issue😢
不过肯定还是要去解决的，可能会拖一会儿

**Comment by pluveto** [comment]
导出后变成了微软雅黑和普通宋体……

**Comment by Keldos-Li** [comment]
> 导出后变成了微软雅黑和普通宋体……

怎么说？

**Comment by pluveto** [comment]
我换成华文中宋之后就好了。估计是宋体的 font-weight 支持不好。

**Comment by Franklyzzm** [comment]
我也是這個問題，引文裏邊，粗體導出正常顯示，就是正文裏的粗體，導出到pdf后就變成普通文本了。

**Comment by MichaelMengy** [comment]
@Keldos-Li @RalXYZ  这个问题好像与浏览器内核有关，我使用edge导出也无法生效，但是换用firefox就可以了
![image](https://user-images.githubusercontent.com/38280896/188852903-1bb12ee2-ea58-482c-81f8-e4fd1d6c80f8.png)
edge的网页
![image](https://user-images.githubusercontent.com/38280896/188853052-d6d88462-c1c8-4962-a634-8c8fabd155cc.png)
换成firefox之后粗体就可以正常显示：
![image](https://user-images.githubusercontent.com/38280896/188853365-6c8c40ef-e1f6-43cd-b5ea-781fb95a01e5.png)

我推测可能是与chromium以及GeekGo（firefox内核）的样式渲染策略有关
chromium在打印为pdf时严格按照media = print的规则执行，使得样式没有完全生效
GeekGo不同，即使是打印时也会完全渲染样式，所以呈现预想的结果。

**Comment by Keldos-Li** [comment]
@MichaelMengy 有可能诶，感谢提供思路！我稍候测试下。

**Comment by Keldos-Li** [comment]
我一定要在假期结束前好好看看这个bug！！！！再丢下去不行了！

目前看macOS上没问题。我待会儿看看win。

**Comment by Keldos-Li** [comment]
这个问题还有吗？我在 Windows 上下载了 Typora v1.5.8，测试导出PDF能成功显示粗体和斜体。
![image](https://user-images.githubusercontent.com/23137268/218694443-d5540de4-4272-4b47-b003-09daa6862235.png)

**Comment by Keldos-Li** [comment]
@deepbluefantasy @Franklyzzm  @MichaelMengy @pluveto @Silver144 能否烦请各位下载一下 [最新版 Typora](https://typora.io/releases/all)，看看是否还有该问题？

**Comment by Keldos-Li** [comment]
如无其他问题，issue「导出PDF时无法呈现粗体和斜体 #74」将在2月25日0:00（北京时间）被关闭。如有问题请尽快反馈。

**Comment by MichaelMengy** [comment]
@Keldos-Li 导出已经没有问题了，粗体正常显示，感谢作者大大！
