### ISSUE TITLE
目录导出不正确

### ISSUE THREAD

**Issue by Torrents-oasis** [Keldos-Li/typora-latex-theme#75]
### 操作系统

Windows 10 家庭版

### 问题描述

- [ ] 导出目录不正确。

### 复现方法

可以根据下面的截图创建相应的目录，并随机填充内容进行复现（我的报告大约24000字符，其中大部分为代码块，可以参考这个样式复现）。
由于是该文档为课程报告，根据诚信手册不能上传，但如果有必要，可以邮件联系沟通，或者紫金港线下提供参考，我的邮箱是317682528@qq.com。

### 预期行为

下图为typora默认主题`GitHub`下的目录样式，是正确的我期望的样式。
![image](https://user-images.githubusercontent.com/69155059/164463341-834dca5a-fbd9-4e9a-85a2-170171774bda.png)

### 屏幕截图

下图为`latex`主题下的目录样式，可以看出并不正确。
![image](https://user-images.githubusercontent.com/69155059/164463226-19a2ffad-107c-4a80-a06b-5aef3fbeb173.png)

### 附加内容

每次开latex编译好麻烦，你们的这个项目真的太方便易用了！

**Comment by RalXYZ** [comment]
感谢你的反馈！❤  
我希望获取这个文档来进行故障排查。如果可以的话，请把文档发送到我的邮箱 [RalXYZ@pm.me](mailto:RalXYZ@pm.me)。  
我们尊重你的隐私，同时也没有任何理由向第三方泄露你的文档内容。希望得到你的理解。

**Comment by Keldos-Li** [comment]
我看截图是第一层级丢掉了？
我们的主题把一级标题（# xxx）视为文章标题，默认一篇文档只允许出现一个大标题且只在文档的最上面，目录里是不包括文章标题的。

如果你没有用到所有六个层级的标题的话，可以试试把每个小标题都减小一个层级，看看能不能解决。

**Comment by Keldos-Li** [comment]
可以解决吗？如果没问题我就close啦 @Torrents-oasis

**Comment by Torrents-oasis** [comment]
确实是标题层级的问题，该主题默认一级标题不加入目录，把所有想加入目录的标题从二级标题开始排就可以正常显示了。

**Comment by Torrents-oasis** [comment]
原来这样，我试试，谢谢啦----------------------------
确实，我把所有层级向下调一层之后问题就解决了，谢谢啦，你们的这个主题超级好用。
附上之前的文档。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Keldos-Li/typora-latex-theme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Keldos-Li/typora-latex-theme] 目录导出不正确 (Issue #75)





 
我看截图是第一层级丢掉了？
 我们的主题把一级标题（# xxx）视为文章标题，默认一篇文档只允许出现一个大标题且只在文档的最上面，目录里是不包括文章标题的。
 
如果你没有用到所有六个层级的标题的话，可以试试把每个小标题都减小一个层级，看看能不能解决。

**Comment by Torrents-oasis** [comment]
可以的，抱歉忘了及时close。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Keldos-Li/typora-latex-theme] 目录导出不正确 (Issue #75)





 
可以解决吗？如果没问题我就close啦 @Torrents-oasis
