### ISSUE TITLE
字体与Mathtype冲突

### ISSUE THREAD

**Issue by QingChuanWS** [Keldos-Li/typora-latex-theme#76]
### 操作系统
Windows 10 21H1

### 问题描述
在按照教程安装之后，完美浮现博客中的效果，但是mathtype显示logo之后闪退

### 复现方法
Mathtype版本：7.4
安装在线教程字体之后尝试打开mathtype即可

### 预期行为
不应与Mathtype冲突，希望楼主能提供更为优秀的字体

### 附加内容
强推项目，但是与mathtype冲突确实麻烦，希望您能给出其他备选字体方案

**Comment by Keldos-Li** [comment]
经检索，能找到多例mathtype与安装中文字体冲突的事例，可见该问题出现原因更可能在mathtype。

另外该issue与本项目关联不大，我也不能解决这个问题。在QQ上与 @QingChuanWS  也有过交流，我决定关掉这个issue。
