### ISSUE TITLE
表格展示上有点不好看

### ISSUE THREAD

**Issue by KarryCharon** [Keldos-Li/typora-latex-theme#81]
以如下的md表格展示的时候 会出现 非常窄的三线表，感觉不太美观

```markdown
     | 语言      | 耗时/s   |
     | :-------- | :------- |
     | python    | 1.687    |
     | lua       | 0.751 |
     | luajit    | 0.388 |
     | c++ (gcc) | 0.420     |
     | c++ (vc)  | 0.074    |
     | rust      | 0.073    |
```

**Comment by Keldos-Li** [comment]
我不太确定您的意思，您是希望默认表格有一个最小宽度？还是希望表格的padding再宽一些？
我不太确定您想实现的效果。不过您的数据确实很窄，我不太清楚标准的LaTeX中会怎样呈现。

我现在可以提供一种折中取巧的办法，您看看行不行。
<img width="865" alt="image" src="https://user-images.githubusercontent.com/23137268/169676174-1acb6953-0db2-477c-bd70-85be03e30e3c.png">

```markdown
| <span style="color:white">〇〇</span>语言<span style="color:white">〇〇〇</span> | <span style="color:white">〇〇</span>耗时/s<span style="color:white">〇〇</span> |
| :--------: | :------: |
| python    | 1.687    |
| lua       | 0.751 |
| luajit    | 0.388 |
| c++ (gcc) | 0.420     |
| c++ (vc)  | 0.074    |
| rust      | 0.073    |
```

如果您希望左列左对齐，您也可以在每个单元格的前面都加上`<span style="color:white">〇〇</span>`。

**Comment by KarryCharon** [comment]
是的 就是感觉太窄了，
![image](https://user-images.githubusercontent.com/49889381/169677009-e579d58e-889b-4d3b-aaba-474d9b531abc.png)

**Comment by KarryCharon** [comment]
不过谢谢你的方案，现在看起来确实好看了些
