### ISSUE TITLE
Windows下的上标无法正常打印

### ISSUE THREAD

**Issue by OLI370** [Keldos-Li/typora-latex-theme#82]
### 操作系统

Windows x64 Typora1.2.5
### 问题描述

根据README安装主题和字体以后，选择主题并打印md文件为pdf时，pdf文件中的上标显示原内容。
### 附加内容
<img width="494" alt="屏幕截图 2022-05-22 115640" src="https://user-images.githubusercontent.com/57079656/169677959-73728c73-a6d2-4401-8972-569dd298c0be.png">

**Comment by OLI370** [comment]
用<sup>标签是可以的，想知道是什么原因？

**Comment by OLI370** [comment]
用sup标签是可以的，想知道是什么原因？

**Comment by Keldos-Li** [comment]
请确保您在设置中打开这个功能：
<img width="736" alt="image" src="https://user-images.githubusercontent.com/23137268/169679341-ad3625e5-d7c9-4f28-9a42-ef43b48fd702.png">

**Comment by Keldos-Li** [comment]
请问解决您的问题了吗？
