### ISSUE TITLE
windows执行install.ps1安装报错

### ISSUE THREAD

**Issue by Knaithe** [Keldos-Li/typora-latex-theme#83]
### 操作系统

windows 10.0.19044
### 问题描述

右键点击 install.ps1 文件，然后点击“使用 PowerShell 运行”
### 屏幕截图

![image](https://user-images.githubusercontent.com/22469662/170621943-395ca6d0-9c34-46fb-b1d3-9e02cf5bfd32.png)

**Comment by KnaitheYuan** [comment]
我自己建了一个target目录，再次执行install.ps1，提示安装成功，再次打开typora并没有主题，也未在C:\Users\xxxx\AppData\Roaming\Typora\themes找到主题文件
![image](https://user-images.githubusercontent.com/22469662/170622623-2d411f52-bc31-44f8-a709-d17b44ad1a40.png)

**Comment by Keldos-Li** [comment]
好吧，我感觉是我们的readme没考虑到clone源码的用户们。之后src里的readme要改一改。

请您下载 [release](https://github.com/Keldos-Li/typora-latex-theme/releases/tag/v0.2.7) 中的 [latex-theme-windows.zip](https://github.com/Keldos-Li/typora-latex-theme/releases/download/v0.2.7/latex-theme-windows.zip)
![image](https://user-images.githubusercontent.com/23137268/170735888-79cb4dd1-ae1a-4c99-8dbd-87d6d9c6060c.png)
解压之后再运行文件夹中的 `install.ps1`。

**仅想使用这套主题的用户请不要直接clone仓库源码**，仓库源码中**不包含**css文件，css文件是通过GitHub Actions编译生成的，如果您克隆了源码，您可以参考[贡献指南](https://github.com/Keldos-Li/typora-latex-theme/wiki/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97#%E6%9E%84%E5%BB%BA%E8%BF%87%E7%A8%8B)在本地编译一套可用的css文件。

**Comment by Keldos-Li** [comment]
@RalXYZ 是不是报错提示也可以相应改一下，提示一下下载release？

**Comment by RalXYZ** [comment]
> @RalXYZ 是不是报错提示也可以相应改一下，提示一下下载release？

支持，接下来我会加一下

**Comment by Knaithe** [comment]
> 好吧，我感觉是我们的readme没考虑到clone源码的用户们。之后src里的readme要改一改。
> 
> 请您下载 [release](https://github.com/Keldos-Li/typora-latex-theme/releases/tag/v0.2.7) 中的 [latex-theme-windows.zip](https://github.com/Keldos-Li/typora-latex-theme/releases/download/v0.2.7/latex-theme-windows.zip) ![image](https://user-images.githubusercontent.com/23137268/170735888-79cb4dd1-ae1a-4c99-8dbd-87d6d9c6060c.png) 解压之后再运行文件夹中的 `install.ps1`。
> 
> **仅想使用这套主题的用户请不要直接clone仓库源码**，仓库源码中**不包含**css文件，css文件是通过GitHub Actions编译生成的，如果您克隆了源码，您可以参考[贡献指南](https://github.com/Keldos-Li/typora-latex-theme/wiki/%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97#%E6%9E%84%E5%BB%BA%E8%BF%87%E7%A8%8B)在本地编译一套可用的css文件。

按照你说的下载release，安装执行成功，问题可以关闭了。
