### ISSUE TITLE
Windows 环境下使用 Family Song 正文字体显示楷体

### ISSUE THREAD

**Issue by HERMIT-OuO** [Keldos-Li/typora-latex-theme#84]
### 操作系统

Windows 11 21H2
### 问题描述

安装字体仓库提供的 Family Song 字体族（4 款字体均完整安装），并在 css 文件中添加 Family Song 字体之后，正文部分显示为楷体。

![image](https://user-images.githubusercontent.com/26111886/172046202-dbadcef3-c933-4abb-b5ad-478d7c979d73.png)

**Comment by Keldos-Li** [comment]
能看一下您在css中是怎么写的吗？我猜测可能是我的字体property设置的时候英文有点问题，导致正文映射成了斜体，或者有些其他问题（？）
所以 family song 确实还得排查再进正式版orz

最近出图周有亿点忙，可能得等等再排查这个问题了。建议您先用其他的字体设置。

**Comment by Keldos-Li** [comment]
我看了下，确实有这个问题。应该是字体打包的时候出问题了。（同时也怪Windows字体支持极差[○･｀Д´･ ○]）

**Comment by HERMIT-OuO** [comment]
> 

没关系您太客气啦，我换了其他的字体族，但是体验都不是太好。不知道 Windows 字体渲染什么时候才能好起来，4K 150% 缩放还是边缘发虚。

**Comment by Keldos-Li** [comment]
您有空测试下新的字体吗，重新写了参数打包，文件有点大放在蓝奏云， https://wwu.lanzouh.com/i96gX06m5s0h

**Comment by HERMIT-OuO** [comment]
Windows 11 21H2 + Typora 1.3.6 下使用正常（字体确实有点大

**Comment by Keldos-Li** [comment]
_(:з」∠)_ 我也不知道为什么改了参数字体重新打包会大，可能字体公司有特殊的压缩技术吧_(:з」∠)_
