### ISSUE TITLE
更新typora到1.3.6后引用上标样式失效

### ISSUE THREAD

**Issue by T-Atlas** [Keldos-Li/typora-latex-theme#86]
### 操作系统
1.3.6 windows

### 问题描述
更新typora到1.3.6后引用上标样式失效

##
![微信截图_20220612113111](https://user-images.githubusercontent.com/69239617/173213184-91de26c1-01c4-4f50-a6ef-cb1aec9a559d.png)
# 附加内容

**Comment by Keldos-Li** [comment]
这个确认勾选了吗
<img width="720" alt="image" src="https://user-images.githubusercontent.com/23137268/173220436-a591da9c-5272-4b5e-86a5-2b44b11a172c.png">

**Comment by T-Atlas** [comment]
ok
