### ISSUE TITLE
使用该主题后的一堆问题，请求帮助

### ISSUE THREAD

**Issue by Yam0214** [Keldos-Li/typora-latex-theme#88]
### Discussed in https://github.com/Keldos-Li/typora-latex-theme/discussions/87

<div type='discussions-op-text'>

<sup>Originally posted by **Yam0214** June 18, 2022</sup>
请原谅这个不明确的标题。我的疑问太多，一时间不知道如何清晰地表述。除却gitee上的图片无法加载，我有几个疑惑希望得到帮助：

## 环境

  * win10
  * Typora 1.3.6

按照README说明，我右键在powershell中运行`install.ps1`文件完成了安装。随后在[typora-latex-theme-fonts](https://github.com/Keldos-Li/typora-latex-theme-fonts)下载了[Family Song.zip](https://github.com/Keldos-Li/typora-latex-theme-fonts/blob/main/General%20platform/Family%20Song.zip)、[Latin Modern.zip](https://github.com/Keldos-Li/typora-latex-theme-fonts/blob/main/General%20platform/Latin%20Modern.zip)和[Alibaba PuHuiTi 2.0.zip](https://github.com/Keldos-Li/typora-latex-theme-fonts/blob/main/Windows/Alibaba%20PuHuiTi%202.0.zip)。

## 遇到的问题

1. 编辑模式字体太小，并且正文的字体大小与代码块的字体大小不匹配。后者要比前者大很多。见下图
    * ![image](https://user-images.githubusercontent.com/40912707/174435395-e28125fb-134d-4785-a330-bc7d1b1258cb.png)
2. 我用Typora打开项目提供的[essay-template.md](https://github.com/Keldos-Li/typora-latex-theme/blob/main/Supplemental/essay-template.md)文件导出pdf文件，但是比项目自带的[essay-template.pdf](https://github.com/Keldos-Li/typora-latex-theme/blob/main/Supplemental/essay-template.pdf)文件要大一倍。（自带的essay-template.pdf文件大小为431KB，而我导出的pdf文件大小为863KB）
3. 导出的pdf文件与自带的[essay-template.pdf](https://github.com/Keldos-Li/typora-latex-theme/blob/main/Supplemental/essay-template.pdf)在显示上也不同。见下图
    * ![image](https://user-images.githubusercontent.com/40912707/174435608-15714989-782b-40c1-a1fe-3cfdd6f9a7c6.png)
    * 左边是自带的pdf，右边是导出的pdf
    * 可以明显的观察出，二者无论是标题、正文、代码块，字体都不相同。
    * 在右边导出的pdf中，依旧是正文字体比代码块字体小，并且比左边自带的pdf的字体小。
    * 如果在Typora的`偏好设置/外观/字体大小`设置为`自动`，则导出的pdf里代码块的字体也一并缩小
4. [essay-template.md](https://github.com/Keldos-Li/typora-latex-theme/blob/main/Supplemental/essay-template.md)文件，在`偏好设置/Markdown/空格与换行`中不勾选”首行缩进“的情况下，预览和导出的pdf都有首行缩进的效果。而我新建的md文件在latex主题下没有首行缩进。

## 我希望达成的效果

1. 我希望自己的Typora在编辑时，正文和代码块的字体都足够大。单纯的放大typora界面仅仅是缓解之计。
2. 我希望自己的Typora在导出pdf后，文件显示效果与[essay-template.pdf](https://github.com/Keldos-Li/typora-latex-theme/blob/main/Supplemental/essay-template.pdf)相似：
    1. 中文段落有首行缩进
    2. 所有字体的大小都合适
    3. （如果能的话，导出的pdf也不要那么大……）

我猜测部分问题源自`latex.cs`文件的字体设置，于是付上改动部分的文件片段

```cs
  --base-Chinese-font: "Family Song", "华文宋体", "Noto Serif CJK SC";
```

这一部分完整代码见下

```cs
:root {
  /* == 字体设置 == */
  /* 基准字体 */
  /* 备选：Times, "Times New Roman" */
  --base-Latin-font: "Latin Modern Roman", "Latin Modern Roman 10";
  --base-Chinese-font: "Family Song", "华文宋体", "Noto Serif CJK SC";
  --base-font-size: 9.5pt;
  /* 引言字体 */
  --quote-font: "Latin Modern Roman", "Latin Modern Roman 10", Times,
    "Times New Roman", "华文仿宋";
  /* 这里字体用了10pt,比正文字体稍大 */
  --quote-font-size: 10pt;
  /* 代码字体（代码中的中文会调用 ui-font） */
  --code-font: "Latin Modern Mono", "Latin Modern Mono 10", "Courier New";
  /* 侧边栏字体 */
  --ui-font: "阿里巴巴普惠体 2.0", "微软雅黑";
  /* source mode 字体 */
  /* 默认调用 code-font 和 ui-font */
  --sourceMode-font: "SF Mono", "阿里巴巴普惠体 2.0", "微软雅黑";
  /* 目录字体 */
  /* 默认调用 base-font */
  --toc-font: "";
  /* 默认调用 base-font-size */
  --toc-font-size: "";
  /* 表格字体 */
  /* 默认调用 heading-font */
  --table-title-font: "";
  /* 默认调用 base-font */
  --table-font: "";
  /* 标题字体（总设置） */
  --heading-Latin-font: var(--base-Latin-font);
  --heading-Chinese-font: "华文黑体";
  /* 标题字体分别设置 */
  /* 大标题（h1）字体 */
  --title-Chinese-font: "华文黑体";
  --title-font-size: 18pt;
  /* h2字体 */
  --h2-Chinese-font: "华文黑体";
  --h2-font-size: 14pt;
  /* h3字体 */
  --h3-Chinese-font: "华文黑体";
  --h3-font-size: 12pt;
  /* h4字体 */
  --h4-Chinese-font: "华文楷体";
  --h4-font-size: 10pt;
  /* h5字体 */
  --h5-Chinese-font: "华文仿宋";
  --h5-font-size: 10pt;
  /* h6字体 */
  --h6-Chinese-font: "华文仿宋";
  --h6-font-size: 9.5pt;
  /* 粗体样式设置 */
  /* 加粗风格时使用的字重；400等同于 normal，700等同于 bold，900等同于 heavy */
  --strong-weight: 900;
  /* 基础行距 */
  --base-line-height: 16pt;
  /* == 页面设置 == */
  /* 打印页边距 */
  --set-margin: 1.8cm 2cm 1.2cm 2cm !important;
  /* == 控制设置 == */
  /* 目录中是否显示一级标题 */
  --toc-show-title: none;
  /* == 颜色设置 == */
  /* 超链接颜色 */
  --link-color-light: #2E67D3;
  --link-color-dark: #8bb1f9;
}
```</div>

**Comment by Keldos-Li** [comment]
代码块的字体大小参看 #85 ，其他的我看你 discussion 里自我解答了哈，基本对的。

正文字体我是默认设得比较小，大概是小五到五号的样子，编辑模式的字体大小是 typora 默认的，没有重新设参数；段首我是手动打`　　`的，因为有些段首不需要缩进，默认段首缩进会有些麻烦，当然您开默认缩进也行的；导出不一样是因为我是以前在 macOS 上用老版本的 Typora 导出的，macOS 和 Windows 用的 CSS 和字体就有点微妙区别哈，而且后面包括 CSS 也有调整但导出版一直没有重新制作，所以 PDF 会不一样哈。

你具体需求上，字体大小合适……emm每个人需求不一样，我就觉得小四太大了orz所以反正自己调整合适就行。看得足够清楚那个参看 #80 ，我现在有是有基本的办法，不知道合不合适，待我们再研究下。PDF导出大小么……真的也没那么大啊，你想小的话建议字体换回更原生一点的字体，别用Family Song，我字体打包还是有点问题呜呜……

明天还有考试，就先这么草草地回了哈_(:з」∠)_

**Comment by Yam0214** [comment]
> 

非常感谢你的回复，很有帮助！（祝考试顺利~）
