### ISSUE TITLE
标题导出为pdf后未显示加粗

### ISSUE THREAD

**Issue by Silver144** [Keldos-Li/typora-latex-theme#89]
你好，我在使用这个theme的时候遇到了加粗显示错误的问题，在typora里预览时正常显示，但是导出为pdf后显示错误，如图所示，第一张图是生成的pdf截图，第二张图是typora中的截图，第三张图是导出为html后的截图
<img width="104" alt="Snipaste_2022-06-24_16-28-28" src="https://user-images.githubusercontent.com/31009165/175497067-f646b166-4564-42bc-aef4-ebdf0d9f20dd.png">
<img width="139" alt="Snipaste_2022-06-24_16-28-39" src="https://user-images.githubusercontent.com/31009165/175497071-bcd004c6-23c2-4b41-866d-b72c1adf7e8a.png">
<img width="116" alt="Snipaste_2022-06-24_16-45-02" src="https://user-images.githubusercontent.com/31009165/175499071-32f06876-af16-49e3-9b68-c8aaa7892fe1.png">

操作系统：windows10 21H1
Typora版本：1.0.3
标题的字体：华文楷体

之前考虑过可能是typora本身的问题，但是使用内置的newsprint主题打印为pdf后显示正常

**Comment by Keldos-Li** [comment]
等我排查下看看哈

**Comment by Keldos-Li** [comment]
很怪，我看表格title的字体也有问题，不知道为什么英文字体是对的，中文字体就不对了。

**Comment by Keldos-Li** [comment]
#74

**Comment by Silver144** [comment]
@Keldos-Li 你好，使用新版本的typora后已可正常显示
