### ISSUE TITLE
gitee图床挂了导致封面校名校徽无法显示

### ISSUE THREAD

**Issue by JK-Oliver** [Keldos-Li/typora-latex-theme#90]
如题，前段时间gitee封了所有图床，故现在md打开之后
<img width="474" alt="image" src="https://user-images.githubusercontent.com/58261093/178130432-2c633277-a4c6-4881-8394-5c4a1d8f917c.png">
希望能迁移到其他图床，或者将原文件上传至GitHub
辛苦了！

**Comment by Keldos-Li** [comment]
可以从现在的main分支下载：https://raw.githubusercontent.com/Keldos-Li/typora-latex-theme/main/Supplemental/essay-template.md
之前的release一直没有重新打包，不好意思。

**Comment by RalXYZ** [comment]
感谢反馈，我刚发现我没发新版。刚刚已经发布了。  
https://github.com/Keldos-Li/typora-latex-theme/releases/tag/v0.2.8

**Comment by JK-Oliver** [comment]
Thanks
