### ISSUE TITLE
导出的PDF文件没有页码

### ISSUE THREAD

**Issue by vidon** [Keldos-Li/typora-latex-theme#97]
### 需求描述
一般的多页文件最好是有页码。

### 需求原因
正式文件一般都是要有页码的，没有页码看着不方便，如果打印出来会更容易在装订的时候搞乱。

**Comment by Keldos-Li** [comment]
这个需求可能需要使用 Typora 自己的功能，请参阅 https://support.typora.io/Export/#header--footer。

另外，因为 Typora 的软件限制，目前还不能做到修改页码的样式，请理解。
_（正因为 Typora 的页码不方便，我自己都是导出无页码文件再在 Adobe Acrobat 里再加一遍页眉页脚的……)_
